# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# WaterfowlModel.py
# Created on: 2017-05-16 15:23:10.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: WaterfowlModel <Workspace> <output> <Imported_natural_flood> <Public_input> <Distirbance_input> 
# Description: The change from ArcMap to ArcPro changed a lot of functions with how models are stored.  I'm attempting to work through more changes by leaving the model in python
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import finaloutput, naturalflood
import arcpy, os, sys, getopt, datetime

def printHelp():
        print 'waterfowlmodel.py -m <waterfowl or flood> -r <MAV or WGCP> -w <workspace folder where geodatabases should reside> -g <geodatabase name>'
        sys.exit(2)
def main(argv):
   aoi = ''
   model = ''
   inworkspace = ''
   ingdb = ''
   try:
      opts, args = getopt.getopt(argv,"hm:r:w:g:",["region=","workspace="])
   except getopt.GetoptError:
           printHelp()
   for opt, arg in opts:
      if opt == '-h':
         printHelp()
      elif opt in ("-m", "--model"):
         model = arg
         if model.lower() not in ("waterfowl", "flood"):
                 print 'Model is incorrect'
                 sys.exit(2)
      elif opt in ("-r", "--region"):
         aoi = arg
         if aoi.lower() not in ("mav", "wgcp"):
                 print 'Region is incorrect'
                 sys.exit(2)
      elif opt in ("-w", "--workspace"):
         inworkspace = arg
         if not (os.path.exists(inworkspace)):
                 print "Workspace folder doesn't exist.  Please create it"
                 sys.exit(2)
      elif opt in ("-g", "--geodatabase"):
         ingdb = arg
         if not (os.path.exists(inworkspace)):
                 print "GDB doesn't exist.  Please create it"
                 sys.exit(2)

   if len(opts) < 4:
        printHelp()
   print 'Region of interest: ', aoi
   print 'Workspace: ', inworkspace
   print 'GDB: ', ingdb

   if model == 'waterfowl':
           finaloutput(aoi.lower(), inworkspace, ingdb)
   elif model == 'flood':
           naturalflood(aoi.lower(), inworkspace, ingdb)
if __name__ == "__main__":
   main(sys.argv[1:])
